### ISSUE TITLE
DFP API for total impressions in a date range

### ISSUE THREAD

**Issue by nratter** [googleads/google-api-ads-ruby#101]
I just want to query the DFP API to see how many total impressions we've had over a time interval. Is the only way to do this to create a report, download it, and parse the downloaded report? Or is there just a query that can return what I need in JSON format?

I understand this may not be a programmatic issue. If you'd like me to ask this somewhere else just let me know! Thanks!

**Comment by mcloonan** [comment]
For product questions, rather than library-specific questions, please ask in the appropriate forum. You can find the DFP API's forum here: https://groups.google.com/forum/#!forum/google-doubleclick-for-publishers-api
