### ISSUE TITLE
Consider upgrading from test/unit to minitest

### ISSUE THREAD

**Issue by mcloonan** [googleads/google-api-ads-ruby#103]
The test/unit library currently used for unit testing may be deprecated. We should investigate minitest as an alternative. Thanks @seuros for the suggestion.

**Comment by seuros** [comment]
I will submit a PR today. I already migrated it.

**Comment by dklimkin** [comment]
Hello seuros, we explored the option to use minitest and agreed it's not worth the migration at this time. Thank you for the suggestion, we'll revisit this should we plan a significant refactoring in the future.
