### ISSUE TITLE
Wrong Ruby Version Specification at Gem Website

### ISSUE THREAD

**Issue by felipegoncalvesmarques** [googleads/google-api-ads-ruby#105]
Hello,

In the rubygems site ([(https://rubygems.org/gems/google-ads-common/versions/0.12.3)]), it is specified Ruby Version >= 0.0

But in the google-ads-common-0.12.3\lib\ads_common\env_check.rb there is the following lines:
MIN_RUBY_VERSION = Gem::Version.new('2.0')
MIN_RUBY_RECOMMENDED_VERSION = Gem::Version.new('2.1')

Giving error when executed with Ruby 1.9.3

**Comment by mcloonan** [comment]
Thanks for the report. I will look into updating our gemspec to include the correct ruby version on the Rubygems site. I apologize for the inconvenience.

**Comment by mcloonan** [comment]
I just pushed a new ads_common gem to fix this issue.
