### ISSUE TITLE
SearchLostISBudget in v201607, Campaign Performance

### ISSUE THREAD

**Issue by michaelmartinnz** [googleads/google-api-ads-ruby#109]
Hi,

I am trying to get SearchLostISBudget in v201607, Campaign Performance.
I did register as a double in  data_service_registry.rb, but didn't work.
any ideas?

AdwordsApi::Errors::ReportXmlError (HTTP code: 400, error type: 'ReportDefinitionError.INVALID_FIELD_NAME_FOR_REPORT', trigger: 'SearchLostISBudget', field path: ''):

thanks

**Comment by mcloonan** [comment]
The Ruby library doesn't validate field names for report requests, so I'm not sure exactly what you mean about data_service_registry.rb.

A field of that name doesn't exist in the Campaign Performance Report. Did you mean [SearchRankLostImpressionShare](https://developers.google.com/adwords/api/docs/appendix/reports/campaign-performance-report#searchranklostimpressionshare)?

I'm closing this as it doesn't seem to be library-specific. You can ask general AdWords API questions on our [forum](https://groups.google.com/forum/#!forum/adwords-api).
