### ISSUE TITLE
Not support version

### ISSUE THREAD

**Issue by jhoynerk** [googleads/google-api-ads-ruby#116]
Hi men

I present the following error message

Error: Environment 'PRODUCTION' does not support version 'v201508'

can you help me?

**Comment by seuros** [comment]
This version was deprecated and is not supported anymore. Upgrade to a v201609

**Comment by dklimkin** [comment]
v201508 seems to be a DFP version, anyway, correct it's deprecated.

Please refer to the deprecation schedule:

  https://developers.google.com/doubleclick-publishers/docs/deprecation
