### ISSUE TITLE
Get Targeted locations by the campaign

### ISSUE THREAD

**Issue by Sohair63** [googleads/google-api-ads-ruby#118]
Any source code to get this information with radius map ? 

I have gone through https://developers.google.com/adwords/api/docs/samples/ruby/targeting, 
Also seen https://developers.google.com/adwords/api/docs/appendix/reports/v201607/campaign-location-target-report, but I am new to adwords, not sure how to retrieve this report.

**Comment by dklimkin** [comment]
Hi Sohair63,

Please consider asking on the AdWords API forum instead, as this is a support question, not a library bug report:

  https://groups.google.com/forum/#!forum/adwords-api

As per the matter, you should use the CampaignCriterionService, the fields available are listed here:

  https://developers.google.com/adwords/api/docs/appendix/selectorfields#v201609-CampaignCriterionService

See Proximity.*
