### ISSUE TITLE
Link broken in wiki entry "API access using own credentials"

### ISSUE THREAD

**Issue by mlovic** [googleads/google-api-ads-ruby#120]
In the wiki page [API access using own credentials (installed application flow)](https://github.com/googleads/google-api-ads-ruby/wiki/API-access-using-own-credentials-(installed-application-flow)#step-2---setting-up-the-client-library), there is a link "AdWords setup_oauth2.rb" which is broken:

> 2. In a terminal, navigate to the OAuth2 example for your product.

>  - AdWords setup_oauth2.rb

It seems to point to an example at `examples/v201601/misc/setup_oauth2.rb`, but that subdirectory `v201601/` no longer exists. I assume it should now point to one of 2016{05, 07, 09}, which I understand are newer versions of the API.

**Comment by mcloonan** [comment]
Thanks! I updated the link to the latest version. In the future since this is a wiki you should be able to edit or at least suggest an edit if you see an error like this.

**Comment by mlovic** [comment]
Oh, I didn't know that was possible. Thanks!
