### ISSUE TITLE
Problems with TSV stream

### ISSUE THREAD

**Issue by RodrigoMZ** [googleads/google-api-ads-ruby#123]
I had some problems when I try to tream the awql report on TSV format.
Response it's most of the times truncated at the end.
`report_utils.get_stream_helper_with_awql(report_query,'TSV',@account_id).each_line do |line| 
    puts line
end`

Can you please help me with this BUG.
CSV format works well, but I have problems with million separators, so I prefer to use TSV
Thanks a lot

**Comment by mcloonan** [comment]
Can you give a specific example of what you mean by "truncated"? Are there lines that are missing data within the line, or are there entire lines that should be returned that aren't, or something else?

**Comment by RodrigoMZ** [comment]
Hi
all the lines are fine until the last one, that have some missing data within the line.

**Comment by RodrigoMZ** [comment]
Hi let me show you an example:
I have this awl report query:
`report_query = 'SELECT CampaignId, Date, CampaignStatus, CampaignName,  Impressions, Clicks ,Cost , Conversions, AllConversions, ConversionValue, AverageCpc, AdvertisingChannelType ' +
              'FROM CAMPAIGN_PERFORMANCE_REPORT ' +
              'WHERE CampaignStatus IN [ENABLED, PAUSED] ' +
              'DURING %s' % date_range`

If I run this...
`report_utils.get_stream_helper_with_awql(report_query,'CSV',@account_id).each_line do |line| 
            puts line
          end`
I have a perfect response with all fields.

but If I run this..
`report_utils.get_stream_helper_with_awql(report_query,'TSV',@account_id).each_line do |line| 
            puts line
          end`
My last line just contains the first 3 fields

**Comment by RodrigoMZ** [comment]
I get variable results if I run it repeatedly, but never proper result on the last line.
Format like 'CSV' works fine all the time.

The reason of not use CSV is that millions are separated by commas, and when we try to split we ruin the data, there are any way to avoid 'comma'

**Comment by mcloonan** [comment]
In the meanwhile, you could either download the whole TSV file without streaming it line by line (see [here](https://github.com/googleads/google-api-ads-ruby/blob/master/adwords_api/examples/v201702/reporting/download_criteria_report_with_awql.rb)), or you could parse the CSV file using the [Ruby CSV](http://ruby-doc.org/stdlib-2.0.0/libdoc/csv/rdoc/CSV.html) class which can deal with commas.

**Comment by RodrigoMZ** [comment]
Ok, thanks
Finally I do like this:
`report_utils.download_report_with_awql(report_query,'TSV',@account_id).each_line do |line|`
and works ;)

**Comment by mcloonan** [comment]
I made a fix to the ReportStream in the latest release.
