### ISSUE TITLE
ReportDownloadError.ERROR_WRITING_REPORT_TO_FILE

### ISSUE THREAD

**Issue by stewartl60** [googleads/google-api-ads-ruby#125]
Recently have been encountering this error:

`AdwordsApi::Errors::ReportXmlError: HTTP code: 500, error type: 'ReportDownloadError.ERROR_WRITING_REPORT_TO_FILE', trigger: 'Unable to create report', field path: ''`

Code that triggers it:
`report_utils.download_report_with_awql(report_query, 'CSV')`

What is making it difficult to troubleshoot is that it does not happen every time. Seems like triggering multiple consecutive calls is the easiest way to reproduce, could this be a memory issue?

**Comment by mcloonan** [comment]
This is not specific to the Ruby library; this is happening across all API requests. Please see this forum thread where updates will be posted: https://groups.google.com/forum/#!topic/adwords-api/KtJyGjp5T6g

**Comment by stewartl60** [comment]
Thanks @mcloonan, appreciate the link.
