### ISSUE TITLE
Can't upgrade google-adwords-api to 0.24.0 because google-dfp-api

### ISSUE THREAD

**Issue by guigs** [googleads/google-api-ads-ruby#130]
I have both `google-adwords-api` and `google-dfp-api` gems in my project. 

I can't upgrade `google-adwords-api` to `0.24.0` because it depends on `'google-ads-common', '~> 0.13.0'` and most recent version of `google-dfp-api` depends on `'google-ads-common', '~> 0.12.6'`

**Comment by mcloonan** [comment]
Thanks for the report. I hadn't considered this use case before. We'll make sure to address this with the next releases for each library, to get them back in sync, and I will keep this in mind for future changes to AdsCommon.

For now if you grab the source code, update the DFP gemspec to point at 0.13.0 and build the gem yourself, that should be a satisfactory workaround.

**Comment by mcloonan** [comment]
DFP and AdWords are now on the same version of the common library with today's AdWords release. I apologize for the inconvenience in the meanwhile.

In the future, we'll make sure to upload new version of both AdWords and DFP for each breaking version of common.
