### ISSUE TITLE
Support rails 3

### ISSUE THREAD

**Issue by robinbortlik** [googleads/google-api-ads-ruby#132]
Hello guys, 

first, thank you very much for your gem which saves us a lot of work. 

We are using yours adwords-api gem in our Rails 3 monolith application and actually we are not able to update adwords-api gem to latest version due to conflict in dependency libraries. 
As latest action_pack version (3.22.5) depends on `Builder ~> 3.0.0` (https://rubygems.org/gems/actionpack/versions/3.2.22.5) and yours google-ads-savon depends on `Builder ~> 3.2`. (https://github.com/googleads/google-api-ads-ruby/commit/adcac47c7b9d52e14bf345494a8799644c67863f )

Solution seems to be quite easy. Just changing Builder dependency to `~> 3.0`. This will allow owners of Rails 3 applications to install this gem without problem. 

Adding screenshot where is should be clearly visible.
![builder](https://user-images.githubusercontent.com/228502/28156526-0e9c3bf0-67ab-11e7-8957-3f2f4215ea1e.png)

Thank you very much for considering this change.

**Comment by dklimkin** [comment]
Hello Robin,

Thank you for reporting this issue. I'll review if we can relax the dependency requirement here.

**Comment by robinbortlik** [comment]
Thank you very much @dklimkin :)

**Comment by dklimkin** [comment]
Fixed in ec3902c5ca03c9334903d4ba8b3901585d4f2d4b

**Comment by robinbortlik** [comment]
Thank you very much for fix @dklimkin

**Comment by m1k3** [comment]
Can you also release this to rubygems?

**Comment by dklimkin** [comment]
Good point, we've missed to release ads-savon with the 1.0.0 release. Should be out soon.

**Comment by mcloonan** [comment]
Sorry about that, ads-savon 1.0.3 gems are published now.
