### ISSUE TITLE
Add support for getting index of nested operation in error response

### ISSUE THREAD

**Issue by amrutjadhav** [googleads/google-api-ads-ruby#136]
Currently, if any operation fails, library allows user to get index of operation which have caused error by using function `AdwordsApi::Utils.operation_index_for_error(error)` which is great. But there is no way to get index of suboperation which caused error.

For eg. Cosider following error
```
{"field_path"=>
      "operations[0].operand.extensionSetting.extensions[2].sitelinkFinalUrls",
     "field_path_elements"=>
      [{"field"=>"operations", "index"=>0},
       {"field"=>"operand"},
       {"field"=>"extensionSetting"},
       {"field"=>"extensions", "index"=>2},
       {"field"=>"sitelinkFinalUrls"}],
     "trigger"=>"",
     "error_string"=>"UrlError.INVALID_URL",
     "api_error_type"=>"UrlError",
     "reason"=>"INVALID_URL",
     "xsi_type"=>"UrlError"}
```
Here third extension of first operation caused error. In this case, user has to manually parse response and get index of extension.
It would be great if you add support for getting index of such nested operations also.
Recently I faced same problem. So I created new function to get index of extension sub operation. 
```
def extension_index_for_error(error)
  if(error && error[:field_path] and error[:field_path].kind_of?(String))
    match = error[:field_path].match(/extensions\[(\d+)\]/)
    return match ? match[1].to_i : nil
  end
  return nil
end #end extension_index_for_error
```

**Comment by mcloonan** [comment]
You can use `field_path_elements` to look this up without needing to use regexes or matching. This was added specifically so that you won't have to parse the `field_path` itself. Would using `field_path_elements` be easier for you?

**Comment by amrutjadhav** [comment]
Yes, I can. But as `field_path` elements contains index of operations also, we can get operation index from `field_path` hash directly. Still library provide `AdwordsApi::Utils.operation_index_for_error(error)` function to access it. So I thought there should be also a function to get index of nested operation also.

**Comment by mcloonan** [comment]
The Utils method to get the index was added to the library to assist in parsing the `field_path` before the `field_path_elements` existed. `field_path` currently only exists for backwards compatibility for old logic written against it, but new logic should be written against the easier-to-use `field_path_elements`, which should not require any additional library functions to be able to parse and use.

**Comment by amrutjadhav** [comment]
Thanx for providing me this information. This clears my doubt about ```field_path``` and ```field_path_elements```. So I don't think there is need to add extra function for parsing ```field_path_elements```.
