### ISSUE TITLE
Shopify UTM is "blocking UTM from the Google Merchant".

### ISSUE THREAD

**Issue by ashleyfulks** [googleads/google-api-ads-ruby#137]
### Problem

This merchant is having an issue where his Google Adwords account is not seeing conversions. He contacted Google about this first and they told him to reach out to us as a UTM parameter set by us is setting the sale event to get stuck in Shopify, not being sent to AdWords.

### Scope

Just this one shop

### Examples

The merchant recently had a marketing campaign. They sold 66 items but none of those items were attributed to their AdWords campaign. They contacted Google and Google sent them to us, citing we are changing the UTM tags which is causing AdWords to not update.

The utm_source=googlepla

Here is the report (sorry cannot save it)
![image](https://screenshot.click/TREBLAB__Reports__Sales_by_marketing_campaign__Shopify_2017-10-05_23-33-09.jpg)
[A link to it. If it works, no save function.](https://treblab.myshopify.com/admin/reports/sales_by_marketing_campaign?startDate=-30d&endDate=today)

![image](https://screenshot.click/joxi_screenshot_1507203722213.png_615_kb_uploaded_October_5_2017_Joxi_2017-10-05_23-36-45.jpg)

#### Expected vs Actual

**Expected**: The merchant's conversions would show up in their AdWords manager.
**Actual**:  According to the merchant conversions are not showing up in the manager

### Replication Steps

I asked the merchant what their process was:

- Installed Google Shopping app to our Shopify store to setup Product feed
- Connected Product feed to Google Merchant Center
- Launched Google Shopping Ads for USA in Adwords account connected to Google Merchant center, where it took our Product feed from opur Shopify store
- When sales started rolling in I noticed that our Shopping Campaign in Adwords doesn't attribute any conversions, where's in the Shopify Analytics I've found in the Marketing source section following "Source: googlepla" Screenshot --> http://joxi.net/4Ak5QDXFMl7LVm . Which means we're actually haveing sales from Google Shopping Campaign ads, but our Adwords account for some reason can't "see" it. 
- After some digging I went to the Google Merchant Center (that's where our Adwords account takes Product Feed) and found following --> http://joxi.ru/n2YbBMpcjyQ9oA
- Adwords redirect which setup on the side of Shopify or somewhere else, cause Google Support (over the phone) said that it's not on their said and they can't do anything about it

### More Information

Zendesk Ticket https://shopify.zendesk.com/agent/tickets/7020328

@Shopify/analytics-stack

**Comment by mcloonan** [comment]
This issue tracker is for issues with the AdWords API Ruby client library only. We can't help with this general support request. If you think that I'm closing this in error, please provide more context for exactly how the Ruby client library is involved with the issue you're having.
