### ISSUE TITLE
NoMethodError :[] for nil

### ISSUE THREAD

**Issue by coreyward** [googleads/google-api-ads-ruby#139]
[This method](https://github.com/googleads/google-api-ads-ruby/blob/master/ads_common/lib/ads_common/auth/oauth2_handler.rb#L78-L82) triggers a `NoMethodError` when an authorization is failing. Presumably `get_token` is returning `nil` and there's no guard.

```ruby
def auth_string(credentials)
  token = get_token(credentials)
  return ::Signet::OAuth2.generate_bearer_authorization_header(
      token[:access_token])
end
```

It would be useful if a more specific exception were raised so it could be handled appropriately (i.e., flagging an authorization as invalid and notifying the user, rather than showing a 500 page with no context).

**Comment by mcloonan** [comment]
Good idea, we should definitely check whether token is nil and give a more descriptive error. Do you have any details on what's going wrong that the token would be returned as nil here causing the issue?

**Comment by coreyward** [comment]
In this case, there isn't a refresh token available on the auth and the provided token is expired. The issue happens fairly often when our devs reuse an account across environments since Google doesn't provide a refresh token for re-authorization.

**Comment by mcloonan** [comment]
I'm not sure why you wouldn't have a refresh token, or in fact how you would even fetch an access token in the first place without a refresh token.

Have you followed the instructions [here](https://developers.google.com/adwords/api/docs/guides/authentication) for **Installed application** and also run [setup_oauth2.rb](https://github.com/googleads/google-api-ads-ruby/blob/master/adwords_api/examples/v201710/misc/setup_oauth2.rb) to generate the refresh token? (Or the equivalent instructions for DFP if you happen to be using that library.)

**Comment by coreyward** [comment]
> I'm not sure why you wouldn't have a refresh token, or in fact how you would even fetch an access token in the first place without a refresh token.

I just told you. 

> Have you followed the instructions here for Installed application and also run setup_oauth2.rb to generate the refresh token? (Or the equivalent instructions for DFP if you happen to be using that library.)

Oy. We use OAuth2 in a web request flow to connect to our users’ Adwords accounts (both manager and non-manager). I assure you, it's not us. We do the same for Facebook, Mailchimp, Google Analytics, and others. They all work brilliantly.

**Comment by mcloonan** [comment]
This is the first complaint I've heard where a user for some reason is unable to retain a refresh token in order to generate new access tokens, either with the web flow or the installed application flow. The installed flow is the more common, hence my assumption, but you can cache refresh tokens on a per-account basis as the user authorizes your app with the web flow as well.

In any case, I will still leave this open until we are able to add a more useful error message for the case you ran into.

**Comment by coreyward** [comment]
For what it's worth, Google is unique in this behavior. Facebook will provide a refresh token on subsequent authorizations without even prompting the user. Mailchimp is even more amenable, generating a non-expiring API token on each auth without invalidating the previous one(s).

**Comment by mcloonan** [comment]
This was fixed in the most recent release.
