### ISSUE TITLE
[INFO - DFP API] How can I access deep data with PQL?

### ISSUE THREAD

**Issue by hamdibayhan** [googleads/google-api-ads-ruby#143]
API = DFP

Hi,

I am able to filter with id the AdUnit using PQL but I cannot filter with ad_unit_sizes width. How can I get AdUnit with width 970 using PQL for below hash:

`{:id=>"54321", :parent_id=>"12345", :has_children=>false, :parent_path=>[{:id=>"12345", :name=>"ca-pub-12300000", :ad_unit_code=>"ca-pub-12300000"}], :name=>"test_970*90", :description=>"test_970*90", :target_window=>"TOP", :status=>"ARCHIVED", :ad_unit_code=>"test_970*90", :ad_unit_sizes=>[{:size=>{:width=>970, :height=>90, :is_aspect_ratio=>false}, :environment_type=>"BROWSER", :full_display_string=>"970x90"}]}`

I found a too few example for PQL, are there more examples for PQL? Where can I found?

**Comment by donovanfm** [comment]
The DFP API doesn't support filtering by Ad Unit size. The [Ad_Unit PQL Table](https://developers.google.com/doubleclick-publishers/docs/reference/v201711/PublisherQueryLanguageService#Ad_Unit) supports filtering by all of the fields listed in the documentation. Using the AdUnitService directly, the [getAdUnitsByStatement](https://developers.google.com/doubleclick-publishers/docs/reference/v201711/InventoryService#getadunitsbystatement) documentation lists which fields are support filtering. 

If you are able to narrow down your search results by using any of these filterable fields, then you can do so to limit your response size. After that, you can write ruby code to filter the results based on `ad_unit[:ad_unit_sizes][:size][:width]` on your end.
