### ISSUE TITLE
Using the examples with my own credentials

### ISSUE THREAD

**Issue by ohaddahan** [googleads/google-api-ads-ruby#144]
I'm trying to run one of the basic examples `get_keywords.rb` , I'm gettting:

> Message: [AuthenticationError.CLIENT_CUSTOMER_ID_IS_REQUIRED @ ; trigger:'<null>']
> Errors:
> 	Error [1]:
> 		field_path: 
> 		trigger: <null>
> 		error_string: AuthenticationError.CLIENT_CUSTOMER_ID_IS_REQUIRED
> 		api_error_type: AuthenticationError
> 		reason: CLIENT_CUSTOMER_ID_IS_REQUIRED
> 		xsi_type: AuthenticationError

Is it possible to use it with my own credentials? Also , I'm not seeing anywhere to insert the `CLIENT_CUSTOMER_ID` in the script.

**Comment by mcloonan** [comment]
All examples have a comment describing how this works. For example: https://github.com/googleads/google-api-ads-ruby/blob/master/adwords_api/examples/v201710/basic_operations/get_campaigns.rb#L24

You need to have a config file. By default the library looks for a file called adwords_api.yml, and it looks in your home directory.

Here is the template for that file, where you can input client customer id and OAuth credentials, as well as other options: https://github.com/googleads/google-api-ads-ruby/blob/master/adwords_api/adwords_api.yml

See our Configuration article for complete details: https://github.com/googleads/google-api-ads-ruby/wiki/Configuration
