### ISSUE TITLE
Duplicated key :v201711 in lib/dfp_api/api_config.rb

### ISSUE THREAD

**Issue by radarek** [googleads/google-api-ads-ruby#145]
Loading google-api-ads-ruby gem generates following warning:

```
/Users/radarek/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/google-dfp-api-1.1.0/lib/dfp_api/api_config.rb:115: warning: key :v201711 is duplicated and overwritten on line 139
```

Duplicated key is present in lines:
https://github.com/googleads/google-api-ads-ruby/blob/52bf6fa6791daaaaf740f59591b79c262fa3fb94/dfp_api/lib/dfp_api/api_config.rb#L115
https://github.com/googleads/google-api-ads-ruby/blob/52bf6fa6791daaaaf740f59591b79c262fa3fb94/dfp_api/lib/dfp_api/api_config.rb#L139

**Comment by mcloonan** [comment]
Thanks for pointing this out. We also noticed this and it will be fixed with the next release of the library.
