### ISSUE TITLE
AdsCommon::Errors::Error: Environment 'PRODUCTION' does not support version 'v201609'

### ISSUE THREAD

**Issue by raysango** [googleads/google-api-ads-ruby#149]
ruby version is 1.9.3
google-adwords-api 0.14.1
google-ads-common 0.9.7

Trying to use ManagedCustomerService with api version :v201609

**Comment by mcloonan** [comment]
Hello, v201609 has been sunset, so you will need to use a newer API version. I also recommend updating to ruby 2.0 or newer, as one of our dependencies no longer supports 1.9.
