### ISSUE TITLE
Upgrade Savon (Savon 1 is deprecated)

### ISSUE THREAD

**Issue by gersmann** [googleads/google-api-ads-ruby#15]
Are there any plans to upgrade to savon 2.x? Savon 1.x has been deprecated for quite a while now and conflicts with quite a few other gems (http://savonrb.com/version1/).

**Comment by jamiequint** [comment]
bump

**Comment by dcleven** [comment]
Now that Ruby 1.9.3 is officially not being maintained anymore as of 2/24/15, and Savon 1 only supports 1.9.3, and Savon 2 supports Ruby 2, I think this needs to be addressed ASAP.

**Comment by mcloonan** [comment]
Savon 2 does not support the complex AdWords API wsdls. I would love to upgrade and put this to rest, but it isn't feasible at the moment. We are looking into alternatives.

**Comment by mcloonan** [comment]
The newest versions of ads_common and adwords_api no longer have a dependency on Savon, rather depending on our own fork of Savon which should not conflict with newer versions. dfp_api will also pick up this change in its next release. Please open a new issue for any problems with the ads_savon library or other client library issues.
