### ISSUE TITLE
how to change client_customer_id programmatically 

### ISSUE THREAD

**Issue by evrenios** [googleads/google-api-ads-ruby#159]
Hello, i have a manager account which have multiple clients attached to it.

any given time, i need to be able to do different api calls for different client ids.

currently i can only do api calls with default api object that loads from adwords_api.yml with 
```ruby
adwords = AdwordsApi::Api.new
```

i tried to create custom objects with

```ruby
adwords = AdwordsApi::Api.new({
  :authentication => {
      :method => 'OAuth2',
      :oauth2_client_id => 'xxxxx',
      :oauth2_client_secret => 'xxxxx',
      :developer_token => 'xxx',
      :client_customer_id => 'xxx',
      :user_agent => 'xxxx'
  },
  :service => {
    :environment => 'PRODUCTION'
  }
})
```

and call authorize method on it but i'm receiving `AdsCommon::Errors::OAuth2VerificationRequired`

i even tried to init with the client id that i wrote to yaml file, and still received that error.

than i tried to give the yaml config specifically, which failed again.

```ruby
adwords = AdwordsApi::Api.new({
  :authentication => {
      :method => 'OAuth2',
      :oauth2_client_id => 'xxxxxxx',
      :oauth2_client_secret => 'xxxxx',
      :developer_token => 'xxxxx,
      :client_customer_id => 'xxxxx',
      :user_agent => 'xxxx'
  },
  :oauth2_token => {
    :refresh_token => 'xxxxx,
    :access_token => 'xxxxx'
  },
  :service => {
    :environment => 'PRODUCTION'
  }
})
```

i also tried to use

use_runtime_config.rb

in https://github.com/googleads/google-api-ads-ruby/blob/master/adwords_api/examples/v201809/misc/use_runtime_config.rb

which gave me this error

```ruby
AdwordsApi::V201809::CustomerService::ApiException: [AuthenticationError.OAUTH_TOKEN_HEADER_INVALID @ ; trigger:'<null>']
```

how can i accomplish this need.

Thanks.

**Comment by mcloonan** [comment]
I'm not sure why those aren't working, but the easiest way to do this would probably be to call:

    adwords.credential_handler.set_credential('client_customer_id', new_value)

Let me know if that works out!

**Comment by evrenios** [comment]
nope didnt work

**Comment by gautam417** [comment]
You need to add the issued_at amd expires_in attributes for the oauth2_token or else it breaks.
```                     
                        oauth2_token:         {
                        access_token:  "xxx",
                        refresh_token: "xxx",
                        issued_at:     "xxx",
                        expires_in:    0
                    },
```
