### ISSUE TITLE
Old Faraday dependency needs updating

### ISSUE THREAD

**Issue by furnish** [googleads/google-api-ads-ruby#168]
google-adwords-api depends on google-ads-common, which depends on signet, which depends on faraday 0.9. That's a 5 year old version of faraday, and so conflicts with 
many other gems that uses faraday given how outdated signet is.

So, Google is regularly updating the adwords API and this gem to keep it super-fresh, yet at the same time pointing at a 5 year old faraday gem causing conflicts all over the place. That seems pretty poor for Google.

Could you please organise dependencies so google-adwords-api can use faraday 0.9 - 0.13 at least? The later versions are essentially just bug fixes, so this should just involve updating the dependency on signet.

I appreciate I could fork things, but (1) I'm new to this, (2) that would involve forking google-adwords-api and also google-ads-common and also signet, which is a real pain given a new version of google-adwords-api comes out every few months and (3) it would make more sense to sort this out on the master.

**Comment by johnrails** [comment]
I too would appreciate a dependency update. I love, and need this gem, but you're locking me into an old version of Faraday which forces me to use an older version of another gem I use in my project.

**Comment by sevab** [comment]
Looks like [signet v0.14](https://github.com/googleapis/signet/releases/tag/signet%2Fv0.14.0) is out and support for Faraday 1.x has been added since signet v0.13.

@donovanfm is an upgrade to a newer version of signet something we can expect in the near future?

**Comment by donovanfm** [comment]
Thanks for the update @sevab. I took a look at this, and the [current signet requirement in this library](https://github.com/googleads/google-api-ads-ruby/blob/master/ads_common/google-ads-common.gemspec#L41) is satisfied by v0.14. I updated both my signet and faraday gems on my machine and things appear to be working with google-ads-common. Are you able to update these gems?

**Comment by donovanfm** [comment]
Closing this issue since it has been resolved by the signet update.
