### ISSUE TITLE
Creating Callout Extensions in Adwords

### ISSUE THREAD

**Issue by gautam417** [googleads/google-api-ads-ruby#171]
I'm noticing that when I create a callout ad extension it always replaces the last entry in ad words. The existing call out feed item gets updated and replaced. How do I keep adding more than one?

**Comment by mcloonan** [comment]
When you set your extensions you always have to specify the full set of new extensions. The update request replaces the previous set with the newly specified set.

So just request the existing one, append your new one to the end of the returned list, and then re-upload.
