### ISSUE TITLE
How to perform authentication client side?

### ISSUE THREAD

**Issue by AdamT213** [googleads/google-api-ads-ruby#173]
I want to use the google adwords api, but I am using Rails in Api-only mode. All the authentication methods I see seem to be assuming that there is a frontend Rails application.  In my case, the frontend is a separate javascript application, making prompting for user permissions impossible with the methods described. Surely, this use case must be supported, so please kindly point me to where in the documentation I can find it. Thanks!

**Comment by mcloonan** [comment]
Since you're trying to authenticate in JavaScript, I don't know how much help I can be. However, a quick search of our OAuth docs led me to this guide on authenticating in a JavaScript web application: https://developers.google.com/identity/protocols/oauth2/javascript-implicit-flow

**Comment by AdamT213** [comment]
@mcloonan the issue is that the adwords api is not in the list of supported apis for client side oauth. Seems very strange that google simply doesn't offer client side oauth to its api, since this is how most modern web apps operate...
