### ISSUE TITLE
Support Rails 6.1

### ISSUE THREAD

**Issue by kataring** [googleads/google-api-ads-ruby#180]
Hello guys,

We are using yours google-dfp-api gem in our Rails 6.1(latest vesion) monolith application and actually we are not able to install  google-dfp-api gem to due to conflict in dependency libraries.

Is it possible to resolve the dependency of `tzinfo` ?

```
$ cat Gemfile
source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.0.1'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails', branch: 'main'
gem 'rails', '~> 6.1.3', '>= 6.1.3.1'

gem 'google-dfp-api', '1.14.0'
```

- `activesupport` has a dependency on `tzinfo (~> 2.0)` and `google-dfp-api` has a dependency on `tzinfo (~> 1.0)`

```
$ bundle install
Fetching gem metadata from https://rubygems.org/............
Resolving dependencies...
Bundler could not find compatible versions for gem "tzinfo":
  In snapshot (Gemfile.lock):
    tzinfo (= 2.0.4)

  In Gemfile:
    rails (~> 6.1.3, >= 6.1.3.1) was resolved to 6.1.3.1, which depends on
      sprockets-rails (>= 2.0.0) was resolved to 3.2.2, which depends on
        activesupport (>= 4.0) was resolved to 6.1.3.1, which depends on
          tzinfo (~> 2.0)

    google-dfp-api (= 1.14.0) was resolved to 1.14.0, which depends on
      tzinfo (~> 1.0)

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.
```

refs. https://github.com/rails/rails/commit/e9425abe33924623b1dce62bd817eace757c2b4e

**Comment by donovanfm** [comment]
Hi, thanks for making us aware of this issue. We should have a new lib release coming up soon with the next API version, so I'll look into changing our dependency requirement with that release.

**Comment by skarmakar** [comment]
@donovanfm thanks for the great work! Would the new release support [new awards api](https://developers.google.com/adwords/api/docs/guides/start)?

**Comment by donovanfm** [comment]
Hey, @skarmakar. Like my colleague said, you'll want to use the new Ruby library for the Google Ads API. In the meantime if you still need this library, I was able to upgrade tzinfo to v2. Grab the latest version (1.15.0) and it should resolve the dependency conflict with activesupport. Thanks for bringing this to our attention!

**Comment by kataring** [comment]
Thank you.
