### ISSUE TITLE
Will this library be sunset with Google AdWords API?

### ISSUE THREAD

**Issue by jpuck** [googleads/google-api-ads-ruby#181]
Today Google announced the [sunset of the Google AdWords API on April 27, 2022](https://ads-developers.googleblog.com/2021/04/upgrade-to-google-ads-api-from-adwords.html).

Should we expect this repository to be archived then as well?

Do you recommend we migrate to the gem for https://github.com/googleads/google-ads-ruby?

**Comment by mcloonan** [comment]
The AdWords portion of this library will be removed when the AdWords API is sunset. You should definitely migrate to the Google Ads API, using the library you linked. I am also active on that GitHub repo so if you encounter any Ruby-specific issues, please file an issue there. If you encounter any generic API issues with the Google Ads API, you can contact our dedicated support team on the [support forum](https://groups.google.com/forum/#!forum/adwords-api).
