### ISSUE TITLE
google-dfp-api gem 1.15.0 not compatible with Rails 5.2

### ISSUE THREAD

**Issue by dcleven** [googleads/google-api-ads-ruby#182]
When trying to update to the 1.15.0 version we found that tzinfo version is pinned at ~2.0 which doesn't work with Rails 5.2 specifically activesupport requires tzinfo ~1.1.

I do not see any reason to require tzinfo 2.0 other than being compatible with Rails 6.1. So I think the version of tzinfo should include 1.1 and 2.0.

**Comment by donovanfm** [comment]
This issue has been fixed in the latest release: https://github.com/googleads/google-api-ads-ruby/blob/beeba3240ff8c3dfa9976995a89ee720f02ae128/ad_manager_api/google-dfp-api.gemspec#L40
