### ISSUE TITLE
How to install google-adwords-api for version of Ruby lower than 2.2.2

### ISSUE THREAD

**Issue by Randima-Lahiru** [googleads/google-api-ads-ruby#183]
Can  you please explain how to install google-adwords-api for ruby version lower than 2.2.2.
Here my ruby version : 
[root@web1 ~]# ruby -v                                                                                                           
ruby 2.0.0p648 (2015-12-16) [x86_64-linux]

Error is  : 
ERROR:  Error installing google-adwords-api:                                                                                     
        httpi requires Ruby version >= 2.3.

**Comment by mcloonan** [comment]
There should be little reason for you to begin using the AdWords API right now, as it is deprecated and will be shut down in April 2022.

Instead, consider our new library: https://github.com/googleads/google-ads-ruby

This uses the Google Ads API, the replacement for the AdWords API.
