### ISSUE TITLE
2.4.0 uses v202305 API version of Google Ad Manager, not v202308

### ISSUE THREAD

**Issue by taras-sarmat** [googleads/google-api-ads-ruby#194]
Hi everyone!

I want to update my project to use the latest version of GAM API:
[v202308](https://developers.google.com/ad-manager/api/rel_notes#v202308)

I updated the gem to the latest version:
`gem 'google-dfp-api', '=2.4.0' `-> but it seems that it still uses previous version [v202305](https://developers.google.com/ad-manager/api/rel_notes#v202305). 

Some testing locally:
```
gem 'google-dfp-api', '=2.4.0'
...
api_client.version
=> :v202305

gem 'google-dfp-api', '=2.3.0' 
...
api_client.version
=> :v202305

gem 'google-dfp-api', '=2.2.0' 
...
api_client.version
=> :v202302
```

Should we wait for a fix?

**Comment by taras-sarmat** [comment]
@christopherseeley Could you check please this issue? Thanks!

**Comment by christopherseeley** [comment]
Thanks for pointing this out. v202308 is available, just not the default. I'll send out a fix.

In the meantime, you can specify it when creating the service:
```
order_service = ad_manager.service(:OrderService, :v202308)
```

**Comment by taras-sarmat** [comment]
@christopherseeley thanks a lot!

**Comment by taras-sarmat** [comment]
Resolved https://github.com/googleads/google-api-ads-ruby/commit/1778b315349f210c8cabe9d57c5e430081e7c5a3#diff-935902af6cc6c6efab4a9acccfba44b928c81e2570a90eb753181d7d962c215fR7
