### ISSUE TITLE
HTTPClient::SendTimeoutError: execution expired

### ISSUE THREAD

**Issue by ResumeNothing** [googleads/google-api-ads-ruby#25]
We've been getting this error while updating Ad Params: HTTPClient::SendTimeoutError: execution expired. For some reason this seems to happen most often between 2am and 4am ET on Mondays and Fridays.

Is it possible to configure send_timeout to be longer? We tried adding it to the connection hash like we did with read_timeout and open_timeout when initializing the API object, but it doesn't seem to have had any effect.

```
connection: {
  read_timeout: 1800,
  open_timeout: 600,
  send_timeout: 600
}
```

**Comment by nicholaschen** [comment]
Hiya,

Apologies, looking at this now, I'm not really 100% sure where you're setting this (or in what context you're trying to extend the timeout for sending a request). Not sure if this is still an issue, but let us know and we'll take a look.

**Comment by ResumeNothing** [comment]
I don't think we're having this issue anymore, but thanks for following up!
