### ISSUE TITLE
Get new access token sometime before expiry

### ISSUE THREAD

**Issue by rocky-jaiswal** [googleads/google-api-ads-ruby#27]
Hi,

I recently attended the Adwords API workshop in Hamburg, there it was mentioned that it is ok to get a new access token before it expires (lets say 45 mins after it is issued).

However if you look at the code for OAuth2 handler for the ruby client (oauth2_handler.rb) -

```
  def get_token(credentials = nil)
    token = super(credentials)
    token = refresh_token! if !@client.nil? && @client.expired?
    return token
  end

  # Refreshes access token from refresh token.
  def refresh_token!()
    return nil if @token.nil? or @token[:refresh_token].nil?
    begin
      @client.refresh!
    rescue Signet::AuthorizationError => e
      raise AdsCommon::Errors::AuthError.new("OAuth2 token refresh failed",
          e, (e.response.nil?) ? nil : e.response.body)
    end
    @token = token_from_client(@client)
    return @token
  end
```

The code says that the token can be refreshed only after it is expired. See line 2 of get_token method.

Just wanted to check if this is intentional or a bug. For us it is important as we have built an OAuth2 service for all our client apps (like you recommended) and we want to send them fresh tokens not ones which are about to expire in 15 secs for example.

**Comment by Sohair63** [comment]
Anyone resolved this yet ? 

```
[INTERNAL_SERVER_ERROR] exception="OAuth2 token refresh failed" backtrace="/usr/local/rvm/gems/ruby-2.3.3/gems/google-ads-common-0.12.6/lib/ads_common/auth/oauth2_handler.rb:100:in `rescue in refresh_token!'

**Comment by dklimkin** [comment]
Hi Sohair63, it's very likely this error is due to a local misconfiguration and not related to the enhancement here. Please reach out to the product (AdWords or DFP) support to look into your specific issue.
AdWords: https://groups.google.com/forum/#!forum/adwords-api
DFP: https://groups.google.com/forum/#!forum/google-doubleclick-for-publishers-api

**Comment by Sohair63** [comment]
Thanks @dklimkin

**Comment by mcloonan** [comment]
This was added with the latest ads-common release.
