### ISSUE TITLE
proxy settings not honored for Auth

### ISSUE THREAD

**Issue by froudy** [googleads/google-api-ads-ruby#33]
Hi. I am specifying proxy settings in the yml file correctly yet authorize is not working.
However once authorized (on another connection) I can use the api for about an hour via the proxy
I am using oauth2 and your sample script setup_oauth2

Tried to find the problem and got as far as: 
/signet-0.5.0/lib/signet/oauth_2/Client.rb inside :
```ruby
def fetch_access_token 
```

My Faraday::Connection instance has ```@proxy=nil ```
```ruby
options[:connection] ||= Faraday.default_connection 
```
I found options[:connection] is always blank!

And here is my timeout error I get, which can help you trace the error

```cmd
ruby/2.0.0/net/http.rb:878:in `initialize': A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. - connect(2) (Errno::ETIMEDOUT)

        from /ruby/2.0.0/net/http.rb:878:in `open'
        from /ruby/2.0.0/net/http.rb:878:in `block in connect'
        from /ruby/2.0.0/timeout.rb:52:in `timeout'
        from /ruby/2.0.0/net/http.rb:877:in `connect'
        from /ruby/2.0.0/net/http.rb:862:in `do_start'
        from /ruby/2.0.0/net/http.rb:851:in `start'
        from /ruby/2.0.0/net/http.rb:1367:in `request'
        from /ruby/gems/2.0.0/gems/faraday-0.9.0.rc6/lib/faraday/adapter/net_http.rb:79:in `perform_request'
        from /ruby/gems/2.0.0/gems/faraday-0.9.0.rc6/lib/faraday/adapter/net_http.rb:38:in `call'
        from /ruby/gems/2.0.0/gems/faraday-0.9.0.rc6/lib/faraday/request/url_encoded.rb:15:in `call'
        from /ruby/gems/2.0.0/gems/signet-0.5.0/lib/signet/oauth_2/client.rb:884:in `fetch_access_token'
        from /ruby/gems/2.0.0/gems/signet-0.5.0/lib/signet/oauth_2/client.rb:911:in `fetch_access_token!'
        from /ruby/gems/2.0.0/gems/signet-0.5.0/lib/signet/oauth_2/client.rb:926:in `refresh!'
        from /ruby/gems/2.0.0/gems/google-ads-common-0.9.5/lib/ads_common/auth/oauth2_handler.rb:93:in `refresh_token!'
        from /ruby/gems/2.0.0/gems/google-ads-common-0.9.5/lib/ads_common/auth/oauth2_handler.rb:83:in `get_token'
        from /ruby/gems/2.0.0/gems/google-ads-common-0.9.5/lib/ads_common/api.rb:117:in `authorize'
        from setup_oauth2 232.rb:44:in `setup_oauth2'
        from setup_oauth2 232.rb:77:in `<main>'
```
Thanks for your help,

Froudy

**Comment by mcloonan** [comment]
We've since updated the version of Signet we're using. Does this problem still persist?

**Comment by mcloonan** [comment]
I'm going to close this, since there's no response. If there is still an issue, please let me know so I can look into it.

**Comment by froudy** [comment]
sorry I couldn't post my reply on the github issue via the website for some
reason.

In the end I found setting an environment variables for proxy settings did
the trick.
HTTPS_PROXY=http://proxydomain.com:8080
HTTP_PROXY=http://proxydomain.com:8080
I haven't tested the new version of signet to see if it will work without
these env variables. But I'm sure it will help others if they want to use a
specific proxy server for their API. Thanks
