### ISSUE TITLE
README for example rails app is all wrong

### ISSUE THREAD

**Issue by jonyt** [googleads/google-api-ads-ruby#35]
I'm not a huge Rails expert but the setup instructions seem to be all wrong. Some examples:

* `bundle install` won't work because there's no Gemfile.
* `rake db:migrate` won't work either.
* Neither will `script/server` to start the server. I believe that would only work on a very old version of Rails and you appear to be using a newer one. 

It would also be helpful to give a link to an explanation for the arduous process of obtaining a developer token.

**Comment by nicholaschen** [comment]
closing this out as obsolete as we changed our release process to pick up the missing files :)
