### ISSUE TITLE
Update adwords_on_rails to latest api specs

### ISSUE THREAD

**Issue by ddeyoung** [googleads/google-api-ads-ruby#41]
The example app is outdated and misleading. Primary example is the required use of client_customer_id for all api requests.

**Comment by mcloonan** [comment]
Hello,

We have improvements to this app planned. Thanks for letting us know to also keep that change in mind while working on the example app.

Thanks!

**Comment by mcloonan** [comment]
We released an updated version of this app that works with the 0.14.2 gem and gets around the login issue you mentioned. There are more improvements planned as well, but I'm going to mark this as resolved.
