### ISSUE TITLE
Getting MCC Account hierarchy.rb broken/impossible for v201409 ?

### ISSUE THREAD

**Issue by barttenbrinke** [googleads/google-api-ads-ruby#42]
The example https://github.com/googleads/google-api-ads-ruby/blob/master/adwords_api/examples/v201409/account_management/get_account_hierarchy.rb is broken for me. According to the API docs: https://developers.google.com/adwords/api/docs/reference/v201409/ManagedCustomerService this requres a customer_client_id to be set. Which is weird to me, as the main goal here is to get the hierarchy for a MCC account. Setting a random has no effect, as the adwords.use_mcc() call prevents the customer_client_id header from being set at all.

Can I get my account hierarchy some other way?

**Comment by mostafaz** [comment]
set your MCC cid as the :client_customer_id: in the yml file, then try

```ruby
  require 'adwords_api'
  API_VERSION = 'v201409'.to_sym
  adwords = AdwordsApi::Api.new(path_to_yml_file)
  selector = {fields: ['Name', 'CustomerId']}
  customer_srv = adwords.service(:ManagedCustomerService, API_VERSION)
  customer_srv.get(selector)
```

**Comment by mcloonan** [comment]
Yes, setting the MCC id as the client customer id is the correct approach.
