### ISSUE TITLE
How to get 'low search volume' keyword status from adwords account?

### ISSUE THREAD

**Issue by rothanachoun** [googleads/google-api-ads-ruby#44]
Any solution to get 'low search volume' of keywords ?
I try on with estimate keyword traffic service but I don't know how to define if it is a 'low search volume' with these result response. https://github.com/googleads/google-api-ads-ruby/blob/master/adwords_api/examples/v201409/optimization/estimate_keyword_traffic.rb

**Comment by mcloonan** [comment]
This is not available via the API.

In the future, you can ask non-library-specific questions in the general [AdWords API forum](https://groups.google.com/forum/#!forum/adwords-api).
