### ISSUE TITLE
API fails when requested data is more than 90 days old

### ISSUE THREAD

**Issue by jonyt** [googleads/google-api-ads-ruby#45]
I didn't see this documented anywhere but it appears that at least for the click performance report you can't request data more than 90 days old. If you do the gem will raise AdwordsApi::Errors::ReportXmlError: AdwordsApi::Errors::ReportXmlError, which is misleading. 

It would be better if this limitation was documented and the error was more informative.

**Comment by dklimkin** [comment]
This was announced here but never made it to the docs:

  http://googleadsdeveloper.blogspot.com/2014/02/changes-to-gclid-field-length-in.html

I'll fix it. Closing bug as it's not a library issue.
