### ISSUE TITLE
Conflict with Google API Client

### ISSUE THREAD

**Issue by Plinpod** [googleads/google-api-ads-ruby#47]
My app is currently using 

google-api-client 

and it is conflicting when I try to install google-adwords-api

here is what I get.

Bundler could not find compatible versions for gem "signet":
  In Gemfile:
    google-adwords-api (>= 0) x86-mingw32 depends on
      google-ads-common (~> 0.9.0) x86-mingw32 depends on
        signet (~> 0.4.4) x86-mingw32

    google-api-client (>= 0) x86-mingw32 depends on
      signet (0.6.0)

Bundler could not find compatible versions for gem "savon":
  In Gemfile:
    google-adwords-api (>= 0) x86-mingw32 depends on
      google-ads-common (~> 0.2.0) x86-mingw32 depends on
        savon (~> 0.9.1) x86-mingw32

    savon (2.9.0)

Bundler could not find compatible versions for gem "httpi":
  In Gemfile:
    google-adwords-api (>= 0) x86-mingw32 depends on
      google-ads-common (~> 0.2.0) x86-mingw32 depends on
        httpi (~> 0.7.9) x86-mingw32

    httpi (2.3.0)

So is it impossible to use google-adwords-api and google-api-client? And also savon 2.9.0 and httpi 2.3.0 ?

Thanks!

**Comment by mcloonan** [comment]
The newest version of ads_common updated the signet dependency to the newest version of the library.

Savon is a known issue and is being tracked in a separate thread. Httpi and savon go hand in hand, so that will get addressed alongside savon, when we are able to resolve that issue.
