### ISSUE TITLE
Dependency on older version on Savon

### ISSUE THREAD

**Issue by puneet-khushwani** [googleads/google-api-ads-ruby#48]
v0.14.1 of google-adwords-api depends on google-ads-common (~>0.9.6). google-ads-common has a hard dependency on ~>1.2.0 of savon, this gem is currently at 2.8.0. Our application has other dependencies on this higher version (~>2.8.0), thus we can not go ahead to use google-adwords-api.

Can we have you to release a new version with upgraded dependencies ?

**Comment by nicholaschen** [comment]
https://github.com/googleads/google-api-ads-ruby/issues/15

This is a known issue (or rather a feature enhancement), the two Savon versions are largely dissimilar, and as mentioned Savon 2 simply doesn't support how we generate our SOAP requests.

I'll mark this as a duplicate for now.
