### ISSUE TITLE
Faraday::SSLError

### ISSUE THREAD

**Issue by fertobar** [googleads/google-api-ads-ruby#52]
Hi!
I'm getting a Farady issue: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed.
There is an option for disable ssl verification?

Any help will be appreciated

**Comment by dklimkin** [comment]
Hello,


Strict validation option is available and it is configurable via config file but we strongly recommend against disabling it, as it opens up a major security issue. Any application ignoring certificates checking is prone to men-in-the-middle attacks.

Please configure your system to include SSL certificates instead.


-Danial.

**Comment by fertobar** [comment]
thanks @dklimkin !
Really was related to the RVM cert issue. After install rbenv no more certificates issues.

**Comment by jmock43** [comment]
Hi fertobar, could you please provide more details on how you resolved this issue? I'm seeing the same problem and have no idea how to fix it. Thanks in advance!

**Comment by fertobar** [comment]
Hi, 
on MAC I uninstalled RVM and I'm using rbenv https://github.com/rbenv/rbenv , with Ruby 2.1.5 . After that all works ok.
According to my tries, seems not related with a specific version of Ruby, because I had similar issue with different versions, and the same versions works ok with rbenv.

Hope that could help
