### ISSUE TITLE
fix(bug): location customer feed service function

### ISSUE THREAD

**Issue by vsrboth** [googleads/google-api-ads-ruby#55]

**Comment by vsrboth** [comment]
@dklimkin I won't be able to commit the changes to this repo.

There is a coding problem whilst sending POST request for the location extension with `CustomerFeedService`. Hope to hear from you soon.

**Comment by mcloonan** [comment]
Can you provide more details on the error you're seeing? What version of the library are you using? What exactly are you trying to do? What's the specific error?

**Comment by vsrboth** [comment]
@mcloonan , kindly find the following detail:

I was following this example on adding a location extension [https://github.com/googleads/google-api-ads-ruby/blob/master/adwords_api/examples/v201502/extensions/add_google_my_business_location_extensions.rb].

Here is the line of codes that caused an errors while sending POST request:

- `:placeholder_types => PLACEHOLDER_TYPE_LOCATION`
This one supposed to be `:placeholder_types => [PLACEHOLDER_TYPE_LOCATION]` based on the api guideline for `placeholderTypes` [https://developers.google.com/adwords/api/docs/reference/v201502/CustomerFeedService.CustomerFeed] 

- `lhsOperand`
In `Ruby`, this should be `lhs_operand`.

**Comment by mcloonan** [comment]
Thank you for the detailed descriptions. My apologies that this slipped through! I will make sure this gets fixed.

**Comment by vsrboth** [comment]
@mcloonan there is still an error prone. Kindly fix this one asap.

` :lhs_operand => {
        :xsi_type => 'ConstantOperand',
        :type => 'BOOLEAN',
        :boolean_value => true
      } `

=> this supposes to be 

`:lhs_operand => [ {
        :xsi_type => 'ConstantOperand',
        :type => 'BOOLEAN',
        :boolean_value => true
      } ]`

[https://developers.google.com/adwords/api/docs/reference/v201502/CustomerFeedService.Function#lhsOperand]
