### ISSUE TITLE
savon gem version 

### ISSUE THREAD

**Issue by davingee** [googleads/google-api-ads-ruby#56]
Hello, 

Would it be possible to not set the version of savon, httpi, and signet in google-ads-common.gemspec, it interferes with other gems that use and keep up to date with these gem versions,

perhaps change

````
  s.add_dependency('savon', '~> 1.2.0')
  s.add_dependency('httpi', '~> 1.1.0')
  s.add_dependency('signet', '~> 0.6.0')
````
to 
````
  s.add_dependency('savon')
  s.add_dependency('httpi')
  s.add_dependency('signet')
````

this works fine for me and allows me to use other Library's that us Savon 2.10.0

Thank you

**Comment by mcloonan** [comment]
No; we've specifically tested our library with Savon 2 and it is incompatible.

We are working on an alternative for this, which will be posted to this repo when it is ready.
