### ISSUE TITLE
Document all library parameters

### ISSUE THREAD

**Issue by dklimkin** [googleads/google-api-ads-ruby#6]
Document all library parameters.

**Comment by cavneb** [comment]
:+1:

**Comment by mcloonan** [comment]
Closing this request for now. I think the examples and [reference docs](https://developers.google.com/adwords/api/docs/reference/) provide adequate context for using the lib.

**Comment by mcloonan** [comment]
Discussed with my team, this is for documenting everything that can go into the yml config. Agreed, it's a good idea to have a complete source for all of those. Reopening.

**Comment by mcloonan** [comment]
Added a guide here: https://github.com/googleads/google-api-ads-ruby/wiki/Configuration
