### ISSUE TITLE
No easy way to handle AuthenticationError's

### ISSUE THREAD

**Issue by fastest963** [googleads/google-api-ads-ruby#60]
When the DFP API returns an `AuthenticationError` the `SavonService` fails to correctly send it back as an `AuthenticationError`. This makes it difficult to directly handle `AuthenticationError`s vs any other API error.

Error:
```
client error: Server application error: Failed to resolve exception (nil is not a symbol),
SOAP fault: (soap:Server) [AuthenticationError.NOT_WHITELISTED_FOR_API_ACCESS @ ] at
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/google-ads-common-0.9.9/lib/ads_common/savon_service.rb:113:in `handle_errors'
```

**Comment by nicholaschen** [comment]
Will take a look sometime next week - although I'm now curious why AuthenticationError is viewed any differently as say... LineItemError to Savon.

**Comment by nicholaschen** [comment]
Also out of curiosity, does this happen with other AuthenticationErrors? or is it this one in particular?

I'd expect that to blow up (there shouldn't be any way for you to handle this outside going into the UI and ticking off that checkbox for API access...)

**Comment by nicholaschen** [comment]
Hi,

Given the nature of the error (namely that nothing you do to catch the error and handle it is resolved without user interaction in the UI), I'm inclined to think this isn't going to help much even if the AuthenticationErrors were wrapped differently.

I'll close this now, but if you have any other questions, definitely let us know.
