### ISSUE TITLE
Example for Setting Values of Custom Field appears to be broken

### ISSUE THREAD

**Issue by pam-** [googleads/google-api-ads-ruby#62]
Hi, this is issue is regarding this: https://github.com/googleads/google-api-ads-ruby/blob/master/dfp_api/examples/v201505/custom_field_service/set_line_item_custom_field_value.rb

I'm following the example and setting the value of my custom field like so:
``` 
    custom_field_value = {
      :custom_field_id => custom_creative_field_id,
      :type => 'CustomFieldValue',
      :value => {:type => 'TextValue', :value => ad.current_design_version.vox_ad_name.to_s}
    }
```

**Comment by banderson623** [comment]
:+1:

**Comment by mcloonan** [comment]
Going to close this, since it's exactly the same as the other one minus some information.
