### ISSUE TITLE
Setting Custom Field Value for Creative. Example seems broken

### ISSUE THREAD

**Issue by pam-** [googleads/google-api-ads-ruby#63]
Hi, this is issue is regarding this: https://github.com/googleads/google-api-ads-ruby/blob/master/dfp_api/examples/v201505/custom_field_service/set_line_item_custom_field_value.rb

I'm following the example and setting the value of my custom field like so:
``` 
    custom_field_value = {
      :custom_field_id => custom_creative_field_id,
      :type => 'CustomFieldValue',
      :value => {:type => 'TextValue', :value => ad.current_design_version.vox_ad_name.to_s}
    }
```
But I keep getting this error: `AdsCommon::Errors::UnexpectedParametersError: [:type, :value]` 
Is there a change in the keys needed for this instance?

**Comment by banderson623** [comment]
:+1:

**Comment by nicholaschen** [comment]
huh.

**Comment by banderson623** [comment]
The heart of it, is what is the expected data type/format for the `:value =>` attribute?

We've tried a handful of different variations, including the one [used in example](https://github.com/googleads/google-api-ads-ruby/blob/master/dfp_api/examples/v201505/custom_field_service/set_line_item_custom_field_value.rb#L115) @pam- mentioned above and we've had no luck.

Is anyone else using custom fields on creatives via the ruby gem?

**Comment by nicholaschen** [comment]
FWIW Pam was told to write in directly to our team and the issue is that the example isn't setting xsi_type (type was incorrect). The current set of examples has been fixed :)

**Comment by banderson623** [comment]
Thanks @nicholaschen ! :star2: Updated docs for the win! :dizzy: :star:
