### ISSUE TITLE
uninitialized constant DfpApiStatement (NameError)

### ISSUE THREAD

**Issue by cleitonfco** [googleads/google-api-ads-ruby#67]
In the **ApproveOrders** Example, is showing this error:

    order_service/approve_orders.rb:40:in `approve_orders': uninitialized constant DfpApiStatement (NameError)

One require is missing:

    require 'dfp_api_statement'

**Comment by nicholaschen** [comment]
There's a few of these that I'm gradually going through to fix :)

**Comment by nicholaschen** [comment]
Hiya - I've gone through and fixed each of these instances (there were 28 distinct ones through the 4 version of DFP examples). You can expect to see these pushed within the next couple of weeks.

I'll leave this issue open until they're pushed. Thanks for reporting! :+1:

**Comment by nicholaschen** [comment]
We've actually moved the dfp_api_statement requirement into the dfp_api module, so the newer examples should all reference this and import it as part of the library.
