### ISSUE TITLE
Bug when trying add CustomCriteria in an LineItem

### ISSUE THREAD

**Issue by cleitonfco** [googleads/google-api-ads-ruby#68]
The DFP API has a bug in **line_item_service**, when trying add a **CustomCriteria** in LineItem. It happens:

    $~/.rvm/gems/ruby-2.1.3/gems/google-ads-common-0.10.1/lib/ads_common/parameters_validator.rb:121:in `check_extra_fields': AdsCommon::Errors::UnexpectedParametersError: [:key_id, :value_ids, :operator] (AdsCommon::Errors::UnexpectedParametersError)

I did a debugging and found the problem in constant LINEITEMSERVICE_TYPES (on file *line_item_service_registry.rb*). Which has:

    :CustomCriteriaSet=>{
      :fields=>[
        {:name=>:logical_operator, :type=>"CustomCriteriaSet.LogicalOperator", :min_occurs=>0, :max_occurs=>1}, 
        {:name=>:children, :type=> "CustomCriteriaNode", :min_occurs=>0, :max_occurs=>:unbounded}
      ], 
      :base=>"CustomCriteriaNode"
    }

should be

    :CustomCriteriaSet=>{
      :fields=>[
        {:name=>:logical_operator, :type=>"CustomCriteriaSet.LogicalOperator", :min_occurs=>0, :max_occurs=>1}, 
        {:name=>:children, :type=> "CustomCriteria", :min_occurs=>0, :max_occurs=>:unbounded}
      ], 
      :base=>"CustomCriteriaNode"
    }

The `:type=> "CustomCriteria"` of the children field fix this bug.

**Comment by nicholaschen** [comment]
Hiya,

So I think there's a bit of confusion here, since setting custom criteria isn't quite as straightforward as including the key_id / value_ids in the creation call. I don't doubt that our syntax in our examples might be wonky (again, fixing that), but do you mind sharing your code? There's a few places where instead of setting 'type' we need to explicitly set 'xsi_type,' and I can't help but feel like this is one of them.

**Comment by cleitonfco** [comment]
Hi @nicholaschen,

I'm using this way:

    custom_criteria = {
      xsi_type: 'CustomCriteria', 
      key_id: 'INSERT_CONTENT_CUSTOM_TARGETING_KEY_ID_HERE'.to_i, 
      value_ids: [ 'INSERT_CONTENT_CUSTOM_TARGETING_VALUE_ID_HERE'.to_i ], 
      operator: 'IS'
    }
    custom_criteria_set = {
      xsi_type: 'CustomCriteriaSet', 
      children: [ custom_criteria ]
    }
    targeting = {
      :custom_targeting => custom_criteria_set,
      :geo_targeting => geo_targeting,
      :inventory_targeting => inventory_targeting
    }

**Comment by nicholaschen** [comment]
ah, so... https://developers.google.com/doubleclick-publishers/docs/reference/v201508/LineItemService.Targeting#customTargeting

You need to explicitly mention that the top level object is not just a CustomCriteriaSet, but that it has an operator of 'OR'
