### ISSUE TITLE
target_custom_criteria.rb example wipes out other targeting

### ISSUE THREAD

**Issue by christopherseeley** [googleads/google-api-ads-ruby#73]
The code example wipes out other targeting settings on the line item:
https://github.com/googleads/google-api-ads-ruby/blob/dfp_api-0.10.1/dfp_api/examples/v201508/line_item_service/target_custom_criteria.rb#L105

**Comment by nicholaschen** [comment]
https://github.com/googleads/google-api-ads-ruby/blob/master/dfp_api/examples/v201511/line_item_service/target_custom_criteria.rb#L105

should take care of this
