### ISSUE TITLE
UnexpectedParameters When Modifying a BudgetOrder

### ISSUE THREAD

**Issue by UvulaBob** [googleads/google-api-ads-ruby#78]
I'm trying to modify a budget order, and I get an UnexpectedParameters exception. Here's my code:

    adwords = AdwordsApi::Api.new
    budget_order_srv = adwords.service(:BudgetOrderService, :v201509)

    budget_order = {
	    :id => 196272963,
	    :budgetOrderName => 'My Budget Order'
     }

    budget_order_operation = {:operator => 'SET', :operand => budget_order}
    return_budget_order = budget_order_srv.mutate([budget_order_operation])
    puts return_budget_order

I'm sure the problem is based in my foggy understanding of how to do anything other than a simple GET with Adwords through Ruby, but this seems like a simple step up from that. What am I doing wrong?

**Comment by dklimkin** [comment]
Try changing to:

budget_order = {
    :id => 196272963,
    :budget_order_name => 'My Budget Order'
 }

See the README on Ruby naming:

  https://github.com/googleads/google-api-ads-ruby/blob/master/adwords_api/README.md#21---ruby-names-for-a-ruby-library
