### ISSUE TITLE
AdsCommon::Errors::ApiException: Failed to resolve exception (nil is not a symbol)

### ISSUE THREAD

**Issue by infinite-monkeys** [googleads/google-api-ads-ruby#81]
Hello.

I'm 99% sure this is a result of an API bug/change, not a client bug, but I'll start here and move to the Google DFP API group if necessary.

I have replicated this on the following gem versions + API versions:

google-dfp-api (0.9.5) + google-ads-common (0.9.9). v201411, v201502, v201505
google-dfp-api (0.10.1) + google-ads-common (0.10.1). v201411, v201502, v201508
google-dfp-api (0.12.1) + google-ads-common (0.11.1) v201411, v201502, v201511

I have seen other people posting recently with the "Failed to resolve exception" error for various other SOAP requests, so it appears that the issue is not specific to my query, but the error comes when I add a custom targeting value that already exists.  The response from the API changed between v201411 and v201502.

Previously, the error XML looked like:

```
(rdb:1) response.http.raw_body
"<soap:Envelope xmlns:soap=\"http://schemas.xmlsoap.org/soap/envelope/\"><soap:Header><ResponseHeader xmlns=\"https://www.google.com/apis/ads/publisher/v201411\"><requestId>19cd921a3c2a78ebde832e73203dc68a</requestId><responseTime>483</responseTime></ResponseHeader></soap:Header><soap:Body><soap:Fault><faultcode>soap:Server</faultcode><faultstring>[CustomTargetingError.VALUE_NAME_DUPLICATE @ name; trigger:'ox']</faultstring><detail><ApiExceptionFault xmlns=\"https://www.google.com/apis/ads/publisher/v201411\"><message>[CustomTargetingError.VALUE_NAME_DUPLICATE @ name; trigger:'ox']</message><ApplicationException.Type>ApiException</ApplicationException.Type><errors xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xsi:type=\"CustomTargetingError\"><fieldPath>name</fieldPath><trigger>ox</trigger><errorString>CustomTargetingError.VALUE_NAME_DUPLICATE</errorString><ApiError.Type>CustomTargetingError</ApiError.Type><reason>VALUE_NAME_DUPLICATE</reason></errors></ApiExceptionFault></detail></soap:Fault></soap:Body></soap:Envelope>"
```

Now it looks like:
```
(rdb:1) response.http.raw_body
"<soap:Envelope xmlns:soap=\"http://schemas.xmlsoap.org/soap/envelope/\"><soap:Header><ResponseHeader xmlns=\"https://www.google.com/apis/ads/publisher/v201508\"><requestId>5d66ee1400ecf43704143130275c14ef</requestId><responseTime>206</responseTime></ResponseHeader></soap:Header><soap:Body><soap:Fault><faultcode>soap:Server</faultcode><faultstring>[CustomTargetingError.VALUE_NAME_DUPLICATE @ name; trigger:'ox']</faultstring><detail><ApiExceptionFault xmlns=\"https://www.google.com/apis/ads/publisher/v201508\"><message>[CustomTargetingError.VALUE_NAME_DUPLICATE @ name; trigger:'ox']</message><errors xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xsi:type=\"CustomTargetingError\"><fieldPath>name</fieldPath><trigger>ox</trigger><errorString>CustomTargetingError.VALUE_NAME_DUPLICATE</errorString><reason>VALUE_NAME_DUPLICATE</reason></errors></ApiExceptionFault></detail></soap:Fault></soap:Body></soap:Envelope>"
```

Missing are:
```
  <ApplicationException.Type>ApiException</ApplicationException.Type>
  <ApiError.Type>CustomTargetingError</ApiError.Type>
````

The ApplicationException.Type is used [here](
https://github.com/googleads/google-api-ads-ruby/blob/master/ads_common/lib/ads_common/savon_service.rb#L135) to give us, e.g. `DfpApi::V201411::CustomTargetingService::ApiException: [CustomTargetingError.VALUE_NAME_DUPLICATE @ name; trigger:'ox']
` instead of `AdsCommon::Errors::ApiException: Failed to resolve exception (nil is not a symbol), SOAP fault: (soap:Server) [CustomTargetingError.VALUE_NAME_DUPLICATE @ name; trigger:'ox']`

I couldn't find any mention of this change on the API release notes.  Do you know whether this change is known and expected?

**Comment by nicholaschen** [comment]
Hiya,

I think this is likely tied to the fact that we removed .type fields from v201502 http://googleadsdeveloper.blogspot.com/2015/02/announcing-release-of-dfp-api-v201502.html, so we'll take a look.

Thanks!

**Comment by nicholaschen** [comment]
So doing more research, it's because the .type field no longer exists in the response, correctly - we should be examining the ApiException directly to pull the xsi_type, but it seems the client lib isn't doing that. I'll look into how to reconfigure this a bit to return a more catchable error (it likely won't be in the same format regardless).

**Comment by infinite-monkeys** [comment]
Ahh, okay.  I didn't realize that change would affect the errors as well, but now that you've pointed it out, it makes perfect sense.

**Comment by nicholaschen** [comment]
Hey Infinite-Monkeys,

FYI I fixed this in ads_common and bumped the version for dfp to pick it up as well:

https://github.com/googleads/google-api-ads-ruby/releases/tag/dfp_api-0.13.1

Cheers!
Nick

**Comment by infinite-monkeys** [comment]
Thanks Nick!
