### ISSUE TITLE
.empty? called on nil in get_stream_helper_with_awql

### ISSUE THREAD

**Issue by benhoxie** [googleads/google-api-ads-ruby#82]
I'm using the rails console to run through the example by hand get familiar with reporting outputs, using  this example: https://github.com/googleads/google-api-ads-ruby/blob/master/adwords_api/examples/v201509/reporting/stream_criteria_report_results.rb

Running the  get_stream_helper_with_awql command on line 58 throws 
>NoMethodError: undefined method `empty?' for nil:NilClass
	from /Users/usernamer/.rvm/gems/ruby-2.2.3/gems/google-adwords-api-0.18.0/lib/adwords_api/report_stream.rb:61:in `each_line'
	from (irb):49
	from /Users/username/.rvm/gems/ruby-2.2.3/gems/railties-4.2.0/lib/rails/commands/console.rb:110:in `start'
	from /Users/username/.rvm/gems/ruby-2.2.3/gems/railties-4.2.0/lib/rails/commands/console.rb:9:in `start'

I guess line 61 should be more like
`       @block.call(leftover_data) unless leftover_data.nil? || leftover_data.empty?() `

from here: https://github.com/googleads/google-api-ads-ruby/blob/master/adwords_api/lib/adwords_api/report_stream.rb

**Comment by mcloonan** [comment]
Thanks for this report. I'll make sure a fix for this makes it into the next gem version.

**Comment by benhoxie** [comment]
Cheers, thanks!

**Comment by mcloonan** [comment]
This should work now as of today's release. Please try upgrading to the newest gem version 0.18.1.
