### ISSUE TITLE
ETA for v201601?

### ISSUE THREAD

**Issue by rachel-carvalho** [googleads/google-api-ads-ruby#83]
I'm beginning to use this library in my project and I would like to know how long in average it takes for the next version to be released. Thank you!

**Comment by mcloonan** [comment]
We're planning to release v201601 support tomorrow. This is unfortunately slower even than we'd like, so we're looking to improve the turnaround time for future releases.

I'm glad to see such quick adoption!

**Comment by rachel-carvalho** [comment]
Thank you for the info, I'll be sure to update it as soon as it's out :)
