### ISSUE TITLE
Conflict with new Google API Client

### ISSUE THREAD

**Issue by anovac** [googleads/google-api-ads-ruby#84]
google-adwords-api needs signet 0.6
google-api-client (0.9) needs signet 0.7

Right now, I am forced to use the older version of google-api-client. When will the google-adwords-api gem be updated to use same version of signet as google-api-client 0.9?

**Comment by mcloonan** [comment]
Thanks for the report. I'll look at either updating our required signet version or relaxing the restrictions to allow the library to pick up new versions, depending on how much is changed with the new version.

**Comment by anovac** [comment]
Thank you. :)

**Comment by sparrovv** [comment]
I stumbled upon that today and it's great that you already working on that. 
Is there any ETA of the new version of the gem? Thanks!

**Comment by mcloonan** [comment]
Should hopefully be by the end of next week, although I'm going to get it in as soon as I'm able to if it's ready earlier.

**Comment by mcloonan** [comment]
The newest version of ads_common has an updated signet dependency.
