### ISSUE TITLE
"LoadError: cannot load such file -- ads_common/api" issue caused by file permission level

### ISSUE THREAD

**Issue by ilkon** [googleads/google-api-ads-ruby#89]
After updating gem google-ads-common to version 0.12.1 the applications stopped loading with the error message in issue title. Even rake commands didn't work due to that error.

The problem got resolved after manual fixing file permissions:
```bash
sudo chmod 755 bundle/ruby/2.2.0/gems/google-ads-common-0.12.1/ -R
```
(I found the solution here: https://github.com/googleads/google-api-ads-ruby/issues/74 so this problem has tendency to repeat)

Please fix file permissions.

**Comment by mcloonan** [comment]
Thanks for the report. We'll look into what may have gone wrong and push out a new gem as soon as we've discovered the issue.

**Comment by nicholaschen** [comment]
So we're working on this - but Github seems to be having some connectivity issues so we're waiting on pushing until we can make sure it's done correctly :)

**Comment by nicholaschen** [comment]
Okay, so a few things have been done today

* we updated the ads common gem with the correct permissions
* we updated the gemspec for DFP to use the newer version of ads common
* we republished the v201605 stubs so that everything should be up-to-date

If anything else seems amiss, let us know!
