### ISSUE TITLE
HTTPI::SSLError: SSL_read:: sslv3 alert bad record mac Error

### ISSUE THREAD

**Issue by rahul342** [googleads/google-api-ads-ruby#92]
I am getting this sslv3 error at different times and I am not able to reproduce this consistently. It seems from some info sslv3 is being disabled on Google servers - http://googledata.org/google-online-security/disabling-sslv3-and-rc4/
While some other infos suggests that it could be possibly mismatch of certificates or something but then I would expect to occur every single API call. Do you have any pointers on this?
Thanks.

```
HTTPI::SSLError: SSL_read:: sslv3 alert bad record mac
/vendor/bundle/ruby/1.9.1/gems/httpi-2.4.1/lib/httpi/adapter/httpclient.rb:28:in `rescue in request'
/vendor/bundle/ruby/1.9.1/gems/httpi-2.4.1/lib/httpi/adapter/httpclient.rb:25:in `request'
/vendor/bundle/ruby/1.9.1/gems/httpi-2.4.1/lib/httpi.rb:161:in `request'
/vendor/bundle/ruby/1.9.1/gems/httpi-2.4.1/lib/httpi.rb:133:in `post'
/vendor/bundle/ruby/1.9.1/gems/google-ads-common-0.11.3/lib/ads_common/http.rb:59:in `post_response'
/vendor/bundle/ruby/1.9.1/gems/google-adwords-api-0.18.1/lib/adwords_api/report_utils.rb:231:in `make_adhoc_request'
/vendor/bundle/ruby/1.9.1/gems/google-adwords-api-0.18.1/lib/adwords_api/report_utils.rb:216:in `get_report_response_with_awql'
/vendor/bundle/ruby/1.9.1/gems/google-adwords-api-0.18.1/lib/adwords_api/report_utils.rb:133:in `download_report_with_awql'
```

**Comment by mcloonan** [comment]
I've never heard of this before. Is there any pattern to when this fails and when it doesn't? Does it always fail for certain services or certain method calls or something else like that?

On an unrelated note, you should upgrade to Ruby 2.0 or later as soon as possible because when v201601 is sunset you will have to upgrade to a new version of the gem which requires Ruby 2.0 and no longer functions on Ruby 1.9.

**Comment by mcloonan** [comment]
I spoke with some coworkers and have confirmed that SSLv3 is no longer supported at all, and that all usage must migrate to another protocol. The way that your requests are working intermittently is probably just going to get worse until none work over time.

Can you share the contents of your adwords_api.yml file here (please sanitize your developer token, client id, client secret, etc.) so that I can see your configuration? Since we haven't gotten any other reports of this, I believe it must have something to do with the specific way you're setting up the library.

**Comment by rahul342** [comment]
@mcloonan: Thank you for looking into this and your suggestions. Much appreciate.

> Is there any pattern to when this fails and when it doesn't? Does it always fail for certain services or certain method calls or something else like that?

Out of my last 6 runs, all of them are while fetching ad groups data (I retrieve labels and campaign data as well). 4 of those 6 were while fetching conversions from AD_GROUP_PERFORMANCE_REPORT and the other 2 were fetching ad group objects (bidding info) from the ad group service.

> On an unrelated note, you should upgrade to Ruby 2.0 or later as soon as possible because when v201601 is sunset you will have to upgrade to a new version of the gem which requires Ruby 2.0 and no longer functions on Ruby 1.9.

Yes. Makes sense. Need to prioritize this higher. I just upgraded to 0.18.3.

There's not a lot of custom config so most stuff should be default. Here's the hash that's passed to `AdwordsApi::Api.new`
```
{:authentication=>
  {:method=>"OAuth2",
   :client_customer_id=>"<account-id>",
   :user_agent=>"Ruby Sample",
   :oauth2_token=>
    {:issued_at=>2014-03-25 02:37:42 +0000,
     :expires_in=>3600,
     :id_token=>nil,
     :access_token=>"<access-token>",
     :refresh_token=>"<refresh-token>"},
   :oauth2_client_secret=>"<secret>",
   :oauth2_client_id=>"<client-id>",
   :developer_token=>"<dev-token>"},
 :service=>{:environment=>"PRODUCTION"},
 :connection=>{:enable_gzip=>true},
 :library=>{:log_level=>"INFO"}}
```
We have multiple accounts that I was processing serially. I parallelized for per account but with the same underlying code/logic and it seems the error has gone for now. But this is still mysterious. Even with serialization, I was creating a new adwords api object per account which, I am guessing, wraps the connection object. I wonder if it had to do with token expiry or something.


Thanks again for your help!

**Comment by mcloonan** [comment]
Is this still an issue? Looking more into "bad record mac" it sounds like there's probably something wrong with your SSL cert. This kind of error is language agnostic, and with no other reports I have to believe it's not actually an issue with the library itself.

**Comment by rahul342** [comment]
@mcloonan Apologies for not following up. The issue has gone for us. We couldn't narrow down the exact cause, but I have strong hunch that it happened occasionally when we were pulling too much data in a single request. We ended up parallelizing our tasks for speed and that reduce the data pull size too. And the error has gone for now. Thank you again for looking into this.
