### ISSUE TITLE
[INFO] Port to Crystal

### ISSUE THREAD

**Issue by Micka33** [googleads/google-api-ads-ruby#93]
@Effilab, We heavily rely on @sidekiq and the library to query the Adwords API.
@mperham already [started porting Sidekiq](https://github.com/mperham/sidekiq.cr) to [Crystal](http://crystal-lang.org/).

Is there any plan to do so with this library ?

**Comment by mcloonan** [comment]
No, there are no plans to support Crystal. We have other client libraries in Java, .NET, Perl, Python, and PHP, if for some reason you want to completely move off Ruby and one of those makes more sense.
