### ISSUE TITLE
ArgumentError: Missing elements in :order! [:include_zero_impressions] after move from v201509 to v201605

### ISSUE THREAD

**Issue by drewswaycool** [googleads/google-api-ads-ruby#95]
I recently moved from v201509 to v201605
I couldn't find any significant breaking changes and yet when I try to generate my report it fails with this error:

`ArgumentError: Missing elements in :order! [:include_zero_impressions]`

my report definition is as follows:

![screen shot 2016-07-22 at 11 49 41 am](https://cloud.githubusercontent.com/assets/3419661/17066040/696bc1ac-5002-11e6-831f-da645199042b.png)

**Comment by mcloonan** [comment]
I'm sorry this change didn't make the ChangeLog. You can no longer specify :include_zero_impressions in the report definition. You must do it in the HTTP header instead.

See the download_criteria_report.rb example for a demonstration of how to do this: https://github.com/googleads/google-api-ads-ruby/blob/master/adwords_api/examples/v201605/reporting/download_criteria_report.rb#L60

I will retroactively add this to the ChangeLog with the next release.
