### ISSUE TITLE
invalid_client using service account auth

### ISSUE THREAD

**Issue by nratter** [googleads/google-api-ads-ruby#96]
I'm currently already setup for service account auth for Google Analytics API access. I'm using the same key for oauth access to DFP. I've followed the instructions [here](https://github.com/googleads/google-api-ads-ruby/wiki/API-access-using-own-credentials-(server-to-server-flow)) and [here](https://developers.google.com/doubleclick-publishers/docs/authentication#service), and I've also made a few more modifications to the yml (changed method to OAUTH2_SERVICE_ACCOUNT, and added OAUTH2_secret for the secret for the filename). However, when I run the following code...

```
    dfp = DfpApi::Api.new
    user_service = dfp.service(:UserService, :v201505)
    user_service.get_current_user
```

I get the following error...

```
Signet::AuthorizationError: Authorization failed.  Server message:
{
  "error" : "invalid_client",
  "error_description" : "The OAuth client was not found."
}
```

Any ideas?

**Comment by nicholaschen** [comment]
Question, are you using a .p12 file or a .json file for your service account?

That more or less determines the other fields you need to set as the type of file does make a difference.

Also as a heads up, v201505 is getting deprecated soon! So please make an effort to move off of it in the near future.

**Comment by nratter** [comment]
Ok good to know about the API version. We are using a p12 file.

Nick

**Comment by nicholaschen** [comment]
Hi (fellow) Nick,

Can you do me a favor and JUST update the yaml to use the file path? I have a suspicion that was all you needed and some of the other fields (OAUTH2_SECRET) are adding additional hash params.

Alternatively, making a new json file isn't *the worst* option you have, you could also set additional scopes in the dfp_api.yml to use in analytics if that's the way you want to proceed.

**Comment by nicholaschen** [comment]
actually, in hindsight - OAUTH2_SECRET needs to be there for the .p12 so that's a bit strange (I was thinking about the json flow). I'd need to think about this some more - obviously it's a bit hard with service accounts since they're blackboxed credentials to us...

**Comment by nratter** [comment]
@nicholaschen should I just create a .json service key under that same project and try that?

**Comment by nicholaschen** [comment]
that would likely be the easiest way (JSON is our recommended file format for service accounts as well) - mind trying that and reporting back?

**Comment by nratter** [comment]
Switched to JSON and still getting the same result.

**Comment by nratter** [comment]
I'm doing it without the yaml now, and running the following code and still getting `invalid_client` back....

```
    service_id = "my_service_id"
    network_code = "my_network_code"
    keyfile = "my_keyfile.json"
    dfp = DfpApi::Api.new(
      {
        authentication: {
          method: 'OAUTH2_SERVICE_ACCOUNT',
          oauth2_issuer: service_id,
          oauth2_keyfile: keyfile,
          application_name: "Analytics",
          network_code: network_code
        }
      }
    )
```

**Comment by nicholaschen** [comment]
Sounds good! I'm going to close this, but rest assured, I'm going to continue looking into seeing what might be wrong with cross-product p12 files... that's a bit of a puzzler :)
