### ISSUE TITLE
v201607 support not working?

### ISSUE THREAD

**Issue by udl** [googleads/google-api-ads-ruby#97]
Hi,

I just wanted to upgrade one of our tools to 201607 and got

```ruby
gems/google-ads-common-0.12.3/lib/ads_common/api.rb:156:in `validate_service_request': Environment 'PRODUCTION' does not support version '201607' (AdsCommon::Errors::Error)
```

with the versions
```
Using google-ads-common 0.12.3
Using google-adwords-api 0.20.1
```

Isn't 201607 supposed to work already?

**Comment by mcloonan** [comment]
I just uninstalled and reinstalled the google-adwords-api from Rubygems to double-check, and I can successfully make requests against version v201607. Are you sure you're specifying the version as `:v201607` and not just as `201607`?

**Comment by udl** [comment]
ah, damn ... you're right! the v was missing. thanks!
