### ISSUE TITLE
AdsCommon::Errors::Error: Environment '' does not support version 'v201605'

### ISSUE THREAD

**Issue by Kinertia** [googleads/google-api-ads-ruby#98]
I'm trying to use this with a test account to get approved for production use. I'm setup properly according to all the directions and have version 0.20.0 of the gem, but I keep getting the below error:

AdsCommon::Errors::Error: Environment '' does not support version 'v201605'

My adwords_api.yml is setup just like the example and is authenticating properly it appears as it has the token and refresh token in there and no errors are coming up, but when I try to hit any service I get the error.

The environment PRODUCTION is set in adwords_api.yml but it says Environment '' like it can't read the environment.

Any ideas what's going on?

**Comment by mcloonan** [comment]
Can you provide your full adwords_api.yml file so I can take a look?

**Comment by Kinertia** [comment]
Hey Sorry didn't get the notification.

Here's the adwords_api.yml (obviously with my actual id, secret, and token removed...but they are there in the actual file.

https://gist.github.com/Kinertia/e7b337725b3994b7d9fb12f453a7bc1f

**Comment by mcloonan** [comment]
You have `environment` specified in the `authentication` section. It instead needs to be in a separate `service` section. It looks like you just accidentally tabbed in the higher-level headings.

For example:

    :authentication:
      :method: OAuth2
      :oauth2_client_id: XXXXX
      # More stuff
    :service:
      :environment: PRODUCTION
    :connection:
      :enable_gzip: false
    :library:
      :log_level: INFO

When in doubt, consult our template file: https://github.com/googleads/google-api-ads-ruby/blob/master/adwords_api/adwords_api.yml

**Comment by Kinertia** [comment]
awesome that worked thanks. Wish I just asked days ago haha
