### ISSUE TITLE
:oauth2_secret is required for OAUTH2_SERVICE_ACCOUNT?

### ISSUE THREAD

**Issue by genghuiluo** [googleads/google-api-ads-ruby#99]
```
/.rvm/gems/ruby-2.3.0/gems/google-ads-common-0.12.3/lib/ads_common/auth/oauth2_service_account_handler.rb:149:in `validate_credentials': Key secret is not included in the credentials. (AdsCommon::Errors::AuthError)
```

And what make me feel strange is why client in [java version](https://github.com/googleads/googleads-java-lib/wiki/API-access-using-own-credentials-(server-to-server-flow)) don't need a secret.

**Comment by mcloonan** [comment]
The :oauth2_secret is required when using .p12 files to authenticate as a service account. If you're using a .json file, the requirements are different.

The .p12 file is encrypted so we need the secret just to be able to read the file. The .json file is not encrypted, so there is no such requirement.

**Comment by mcloonan** [comment]
I'm going to close this since you haven't responded in a while. If you're still having trouble, let me know and we can reopen to take another look.
